// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZespolBackend;

#nullable disable

namespace ZespolBackend.Migrations
{
    [DbContext(typeof(ZespolDbContext))]
    partial class ZespolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZespolBackend.CzlonekZespolu", b =>
                {
                    b.Property<int>("CzłonekZespoluld")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CzłonekZespoluld"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktywny")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataUrodzenia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataWstapienia")
                        .HasColumnType("datetime2");

                    b.Property<string>("FunkcjaWZespole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Plec")
                        .HasColumnType("int");

                    b.Property<int>("ZespolId")
                        .HasColumnType("int");

                    b.Property<int?>("ZespolId1")
                        .HasColumnType("int");

                    b.HasKey("CzłonekZespoluld");

                    b.HasIndex("ZespolId");

                    b.HasIndex("ZespolId1");

                    b.ToTable("Czlonkowie");
                });

            modelBuilder.Entity("ZespolBackend.KierownikZespolu", b =>
                {
                    b.Property<int>("KierownikZespoluId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KierownikZespoluId"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataUrodzenia")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoswiadczenieKierownika")
                        .HasColumnType("int");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LiczbaProjektow")
                        .HasColumnType("int");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Plec")
                        .HasColumnType("int");

                    b.Property<long>("TelefonKontaktowy")
                        .HasColumnType("bigint");

                    b.HasKey("KierownikZespoluId");

                    b.ToTable("Kierownicy");
                });

            modelBuilder.Entity("ZespolBackend.Zespol", b =>
                {
                    b.Property<int>("ZespolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZespolId"));

                    b.Property<int>("KierownikZespoluId")
                        .HasColumnType("int");

                    b.Property<int>("KierownikZespoluId1")
                        .HasColumnType("int");

                    b.Property<int>("LiczbaAktywnychCzlonkowZespolu")
                        .HasColumnType("int");

                    b.Property<string>("NazwaZespolu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ZespolId");

                    b.HasIndex("KierownikZespoluId");

                    b.HasIndex("KierownikZespoluId1");

                    b.ToTable("Zespoly");
                });

            modelBuilder.Entity("ZespolBackend.CzlonekZespolu", b =>
                {
                    b.HasOne("ZespolBackend.Zespol", "Zespol")
                        .WithMany("CzlonkowieZespolu")
                        .HasForeignKey("ZespolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZespolBackend.Zespol", null)
                        .WithMany("Czlonkowie")
                        .HasForeignKey("ZespolId1");

                    b.Navigation("Zespol");
                });

            modelBuilder.Entity("ZespolBackend.Zespol", b =>
                {
                    b.HasOne("ZespolBackend.KierownikZespolu", "Kierownik")
                        .WithMany()
                        .HasForeignKey("KierownikZespoluId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZespolBackend.KierownikZespolu", "KierownikZespolu")
                        .WithMany()
                        .HasForeignKey("KierownikZespoluId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kierownik");

                    b.Navigation("KierownikZespolu");
                });

            modelBuilder.Entity("ZespolBackend.Zespol", b =>
                {
                    b.Navigation("Czlonkowie");

                    b.Navigation("CzlonkowieZespolu");
                });
#pragma warning restore 612, 618
        }
    }
}
